apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "auth.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "auth.name" . }}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ include "auth.name" . | quote }}
        dapr.io/app-port: {{.Values.appPort | quote }}
        dapr.io/config: {{ .Values.daprConfig }}
      labels:
        app: {{ include "auth.name" . }}
    spec:
      {{- if .imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ include "auth.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.appPort }}
          env:
            - name: KEEL_PRIVATE_STORE
              value: {{ printf "%s-redis-private-store" .Values.middleware.name }}
            - name: KEEL_PUBLIC_STORE
              value: {{ printf "%s-redis-public-store" .Values.middleware.name }}